version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillsharing-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/skillsharing
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=postgres
      - JWT_SECRET=your-jwt-secret-key
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GOOGLE_REDIRECT_URI=http://localhost:8080/oauth2/callback/google
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - skillsharing-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: skillsharing-db
    environment:
      - POSTGRES_DB=skillsharing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skillsharing-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: skillsharing-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillsharing-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: skillsharing-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - skillsharing-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  skillsharing-network:
    driver: bridge
